name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/" # Change this to the path of your React app (usually "/")
          output_location: "build" # Change this to your React app's build directory
          route_prefix: "/" # Change this if your app is not hosted at the root
